config/routes.rb
Rails.application.routes.draw do

  resources :jobs
  root 'jobs#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  validates :title, presence: true
  validates :company, presence: true
  validates :url, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @jobs = Job.page(params[:page]).per(5)
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(params.require(:job).permit(:title, :company, :url))
    if @job.save
      redirect_to root_path
    else
      render "new"
    end
  end

  def destroy
      @job = Job.find(params[:id])
      @job.destroy!
      redirect_to job_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/index.html.erb
<div class="container">
<%= link_to "Add a job", new_job_path %>
</div>
<h1>Jobs</h1>
<div class="container">
 <table class="table">
  <thead>
    <tr>
      <th>Job name</th>
      <th>Company</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= link_to job.title, job.url %></td>
        <td><%= job.company %></td>
        <td>
          <%= link_to "Delete", job_path(job), method: :delete, data: {confirm: "Really delete this job?"} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<p><%= paginate @jobs %></p>

app/views/jobs/new.html.erb
<div class="container">
  <%= simple_form_for @job do |form| %>
    <%= form.input :title, label: "Job title" %>
    <%= form.input :company, label: "Your company" %>
    <%= form.input :url, label: "Link to job" %>
    <%= form.button :submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jobsboard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>